# Build settings
markdown: kramdown
highlighter: pygments
gems:
  - jemoji

# Site settings
title: "Milan Milanov's blog"
description: "My thoughts around programming"

email: milanov@null.net

#blog logo
logo: "/assets/images/logo.png"

name: 'Milan Milanov'
author: 'Milan Milanov'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://milanov.github.io/" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/milan0v
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/milanov
    desc:	Fork me on github

  - icon: linkedin
    url:  https://bg.linkedin.com/in/milanmilanov
    desc: LinkedIn profile

  - icon: stack-overflow
    url:  http://stackoverflow.com/users/4334499/milan-milanov
    desc: StackOverlow profile

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
